# This file provides instructions for packaging.

`Type-Params`
	perl_version_from m`Type::Params`;
	version_from      m`Type::Params`;
	readme_from       m`Type::Params`;
	requires          p`Eval::Closure`;
	requires          p`Sub::Exporter::Progressive`;
	requires          p`Type::Tiny 0.003_01`;
	test_requires     p`Test::More 0.88`;
	test_requires     p`Test::Fatal`;
	.

